### ISSUE TITLE
Front end ui tweaks

### ISSUE THREAD

**Issue by user2745** [AthleteX-DAO/ax_dapp#258]
- [ ] Add PlayerID stat on page
- [ ] change' input ax' for mint dialog into, create APT pairs

**Comment by bekchanovj** [comment]
Changes on mint popup (Scount -> Athlete page -> Mint):
'Input AX' -> 'Input amount of {athlete_name} APT to mint'. And obviously change the logo from AX to athlete's APT. 
'You receive: ... APTs' -> 'You spend ... AX'
